# -*- coding: utf-8 -*-
"""3.Division_datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PomwD8lvu-G5SOOQkWcIBuAVz_7DAE-r
"""

#@title 3.Division_datos X - Y Credit failure prediction

from sklearn.model_selection import train_test_split

def dividir_datos(df, target='Impago2Años', test_size=0.2, random_state=42):
    """
    Separa el dataset en variables predictoras X y variable objetivo y,
    y realiza la división en conjunto de entrenamiento y prueba.

    Parámetros:
    - df: DataFrame limpio
    - target: Nombre de la columna objetivo
    - test_size: Proporción del conjunto de prueba (default 0.2)
    - random_state: Semilla para reproducibilidad (default 42)

    Devuelve:
    - X_train, X_test, y_train, y_test
    """
    # Separar variables predictoras y objetivo
    X = df.drop(columns=target)
    y = df[target]

    # División estratificada
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, stratify=y, random_state=random_state
    )

    print(f"División de datos completada:")
    print(f"Train: {X_train.shape[0]} muestras")
    print(f"Test:  {X_test.shape[0]} muestras")

    return X_train, X_test, y_train, y_test